// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: foundrytools/options.proto

package foundrytoolspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_foundrytools_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         52000,
		Name:          "foundrytools.namespace",
		Tag:           "bytes,52000,opt,name=namespace",
		Filename:      "foundrytools/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         52001,
		Name:          "foundrytools.type_prefix",
		Tag:           "bytes,52001,opt,name=type_prefix",
		Filename:      "foundrytools/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         52002,
		Name:          "foundrytools.emit_runtime",
		Tag:           "varint,52002,opt,name=emit_runtime",
		Filename:      "foundrytools/options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional string namespace = 52000;
	E_Namespace = &file_foundrytools_options_proto_extTypes[0]
	// optional string type_prefix = 52001;
	E_TypePrefix = &file_foundrytools_options_proto_extTypes[1]
	// optional bool emit_runtime = 52002;
	E_EmitRuntime = &file_foundrytools_options_proto_extTypes[2]
)

var File_foundrytools_options_proto protoreflect.FileDescriptor

const file_foundrytools_options_proto_rawDesc = "" +
	"\n" +
	"\x1afoundrytools/options.proto\x12\ffoundrytools\x1a google/protobuf/descriptor.proto:<\n" +
	"\tnamespace\x12\x1c.google.protobuf.FileOptions\x18\xa0\x96\x03 \x01(\tR\tnamespace:?\n" +
	"\vtype_prefix\x12\x1c.google.protobuf.FileOptions\x18\xa1\x96\x03 \x01(\tR\n" +
	"typePrefix:A\n" +
	"\femit_runtime\x12\x1c.google.protobuf.FileOptions\x18\xa2\x96\x03 \x01(\bR\vemitRuntimeBAZ?github.com/cafecito-games/foundry-tools/internal/foundrytoolspb"

var file_foundrytools_options_proto_goTypes = []any{
	(*descriptorpb.FileOptions)(nil), // 0: google.protobuf.FileOptions
}
var file_foundrytools_options_proto_depIdxs = []int32{
	0, // 0: foundrytools.namespace:extendee -> google.protobuf.FileOptions
	0, // 1: foundrytools.type_prefix:extendee -> google.protobuf.FileOptions
	0, // 2: foundrytools.emit_runtime:extendee -> google.protobuf.FileOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_foundrytools_options_proto_init() }
func file_foundrytools_options_proto_init() {
	if File_foundrytools_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foundrytools_options_proto_rawDesc), len(file_foundrytools_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_foundrytools_options_proto_goTypes,
		DependencyIndexes: file_foundrytools_options_proto_depIdxs,
		ExtensionInfos:    file_foundrytools_options_proto_extTypes,
	}.Build()
	File_foundrytools_options_proto = out.File
	file_foundrytools_options_proto_goTypes = nil
	file_foundrytools_options_proto_depIdxs = nil
}
